const fs = require('fs').promises;
const minify = require('html-minifier').minify;
const puppeteer = require('puppeteer');

const server = require('./server.js');

function minifyHtml(html) {
  return minify(html, {
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    removeAttributeQuotes: true,
    removeOptionalTags: true,
  });
}

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await server.start(9001);
  await page.goto('http://localhost:9001/');
  await page.waitForSelector('.passing');
  await page.evaluate(() => {
    document.querySelectorAll('scripts').forEach(script => script.remove());
  });
  const html = await page.content();
  await fs.writeFile('dist/index.html', minifyHtml(html));
  await browser.close();
  await server.stop();
}

main();
